### ISSUE TITLE
How can I escape '{' and '}' characters in my strings

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [vitiral/strfmt#14]
I have a string like this:

flowrlib = { path = '../flowrlib', version = '*' }

in the template I'd like to process with strfmt, how can I escape the brackets?

**Comment by vitiral** [comment]
{{ and }} should work (like they do in python and rust), let me know if
they don't!

**Comment by vitiral** [comment]
closing, let me know if that doesn't work
