### ISSUE TITLE
Support for other HashMaps in a general way?

### ISSUE THREAD

**Issue by Boscop** [vitiral/strfmt#17]
People sometimes use faster hash functions for strings, are they all supported (as long as they are based on the std HashMap but with a different hasher)?

**Comment by vitiral** [comment]
I wish there was a `Map` trait. Do you have any other ideas of how this
could be done?

**Comment by rardiol** [comment]
One attempt: https://github.com/vitiral/strfmt/pull/21

**Comment by Boscop** [comment]
@vitiral You could just make it generic over the hasher and use std HashMap. It wouldn't require a `Map` trait. (Only if you want to accept non-std `HashMap`s which I didn't mean here.)

**Comment by vitiral** [comment]
Yes sorry @rardiol I should have been more clear. I really don't want to add a specialized `Map` trait to just this library.

**Comment by luketpeterson** [comment]
What about using the `Index` trait, where `Idx: Hash + Eq + FromStr, Output: ?Sized + DisplayStr`?

Basically, the same bounds as are currently on the HashMap's types.

If you agree that this might be a direction worth pursuing, I'll prototype the necessary changes.

Thank you.

**Comment by vitiral** [comment]
Let's make it clear which API we are talking about?

Is it the K type in [Format.format](https://docs.rs/strfmt/0.2.3/strfmt/trait.Format.html)? 

Or the K type in [strfmt::strfmt](https://docs.rs/strfmt/0.2.3/strfmt/fn.strfmt.html)?

Or both? Or are we talking about replacing the whole Map object somehow?

**Comment by luketpeterson** [comment]
> Let's make it clear which API we are talking about?

I was thinking something like this:
```rust
pub fn strfmt<'a, K, Q, T: DisplayStr>(fmtstr: &str, vars: impl Index<&'a Q, Output=T>) -> Result<String>
```
Mirroring the implementation of Index on HashMap here:
https://doc.rust-lang.org/std/collections/struct.HashMap.html#impl-Index%3C%26Q%3E-for-HashMap%3CK%2C%20V%2C%20S%3E

It's probably a moot point because I don't think there's a way to avoid the panic in places where the format string specifies a key that isn't in the HashMap.

**Comment by vitiral** [comment]
I'm not sure I follow completely and don't have time to dig deeply into the library architecture. If you feel strongly about it, feel free to create a MVP with some example usages in tests and I can review it.

**Comment by sanderpick** [comment]
Somewhat related: it would be nice if there was support for `serde_json::Map`. That could look like a trait for `serde_json::Map` that lets you do something like `my_map.formatted(template)`

**Comment by vitiral** [comment]
I will not support this unless rust introduces a `Map` trait.

If you need specialized support please use https://docs.rs/strfmt/latest/strfmt/fn.strfmt_map.html#

We should work to make that API more stable. If someone would like to add tests and confirm it works then we can stabilize that instead.
