### ISSUE TITLE
Alignment does not match description for std::fmt

### ISSUE THREAD

**Issue by MikaelSmith** [vitiral/strfmt#19]
The description on https://doc.rust-lang.org/std/fmt/#width specifies default left-align for strings, right-align for numbers. This library seems to right-align everything by default.

**Comment by vitiral** [comment]
Thanks for the bug.

I'm not actively maintaining this crate, but if you have a PR with the fix and tests I will merge it and push a new version.

**Comment by MikaelSmith** [comment]
PR opened.
