### ISSUE TITLE
Use a closure or a trait instead of HashMap

### ISSUE THREAD

**Issue by theMonttu** [vitiral/strfmt#2]
I have a situation in one of my own projects where I need to format a struct with user provided format string. This crate would be perfect for the job if the interface wasn't so restricted.

I propose that `strfmt_options` should accept a closure that maps the field name into a value, or it could take an object which implements a trait with method that does the same thing. Convenience functions (such as ones accepting `HashMap` or an object with the trait) would be easy to build on top of closure accepting `strfmt_options`.

**Comment by vitiral** [comment]
Hmm, interesting. I'm thinking of the API and I think it should be:

```
/// possible outputs from the closure
enum Replace {
    Value(String), // the value will be used for the format
    Ignore,           // the identifier will be ignored (format string will be written back, same as ignore_mising=true
    Err(String),    // the given error will be returned
};

/// replace items in a string using a closure
fn strfmt_map(s: &str, f: &Fn(identifier: &str, format: &str) 
                      -> Replace;
```

Does this work for you? Any thoughts? I'm going to put a bit more thought into this, but I think something like this would definitely be useful.

Note: eventually a `String.format_map` method could be added to the `Format` trait as well.

**Comment by vitiral** [comment]
I've actually realized that the "use a closure" solution can extend much futher... I could even support integers and the other types!

It will take me a few days to get this implemented, but I am going to be doing it.

**Comment by theMonttu** [comment]
Rather than implementing a new return type, you could use `Result<Option<A>, B>`. This way anyone who reads the function definition knows immediately what exactly is to be returned without the need to search the documentation for the `Replace` enum. Both return types work and of course this is only fine-tuning.

Any type should be possible to be returned as an error as the library doesn't do anything with it, it is just passed back to the user in case an error occurs. Restricting the error to be a `String` is an unnecessary and artificial restriction. 

Also, the closure could support returning anything that implements `ToString` which in turn is implemented automatically for anything that implements `Display`. This way virtually anything that can be turned into text can be returned from the closure and implementing these traits for custom types is easy.

**Comment by vitiral** [comment]
I'm actually going a differen't route for the closure.

First, I am going to implement a public struct which is similar to the `FmtChunk` struct that exists:

```
struct Fmt {
    pub key: &str,  // the key for you to use
    // some fields not listed
    write_to: &mut String, // private stream where Fmt will write to
}

/// choose a type and format a value
impl Fmt {
    fn str(self, s: &str) -> Result<()>; // format as a string
    fn i64(self, i: i64) -> Result<()>; // format as an int
    fn u64(self, u: u64) -> Result<()>; // format as a uint
    fn f64(self, f: f64) -> Result<()>; // format as a float
    fn ignore(self) -> Ok(()); // put the fmt string back exactly as it was.
    // etc.
}
```
All of these methods write the value to the `write_to` stream as the format has specified. If there is an error, they return that error. `ignore` will write the original format string verbatum to the `write_to` stream.

Then the functions will look like this:
```
fn strfmt_map(s: &str, f: &Fn(fmt: Fmt)) -> Result<()>;

trait Format {
    fn format_map(&self, s: &str, f: &Fn(fmt: Fmt)) -> Result<()>;
}
```

I think the first (unstable) implementation of `Result` will just be `Result<T, FmtError>`

I'm not super well versed on exactly how rust's Trait system can be used to do dynamic typing. I'll have to play with that aspect more -- feedback would be very useful!

I haven't decided yet if I'll make `write_to` public -- making it public would let the user do whatever they wanted to the stream which would certainly be powerful (but also potentially confusing). I'm thinking that if the user had a special implementation that they would just be implementing a trait on `Fmt` and would have access to it's private fields.

What will this mean? Eventually, the `format` trait will look like this:

```
trait Format {
    fn format_map(&self, f: &Fn(fmt: Fmt)) -> Result<()>;
    fn format(&self, HashMap<String, String>) -> Result<()>;
    fn format_i64(&self, HashMap<String, i64>) -> Result<()>;
    fn format_f64(&self, HashMap<String, f64>) -> Result<()>;
    // ... etc
}
```

This means if you have a dynamic type you can use `format_map`, but if all your values are a known type you can use one of the helpers. They will all be implemented using `format_map` and a simple closure.

Sorry that got so long, any thoughts?

**Comment by vitiral** [comment]
hmm, I supoose I could also have the closure just return the enum:
```
enum Replace {
    String(String), // the value will be used for the format
    UInt(u64), // use a uint
    Int(i64), // use an integer
    Float(f64), // use a float
    Ignore,           // the identifier will be ignored (format string will be written back, same as ignore_mising=true
    Err(T),    // the given error will be returned
};
```

That would make a certain amount of sense and would also probably be simpler...

**Comment by vitiral** [comment]
Also, I don't think it is sufficient for the type to just implement `display`. If you want to format it according to the format specifier you need to know the exact type (`int` will be formatted differently than `float` which is different than `String`).

**Comment by theMonttu** [comment]
Even though passing an formatter to the closure seems really cool, it is probably overkill as closure needs to return one value at a time. That said, I think returning an enum is the way to go, it's more simple and easier to implement.

On the other hand the formatter passed to the closure could give access to the formatting options, so that it could adapt it's output based on them. Similarly to what's done in `std::fmt::Formatter`. Though access to them isn't that often needed, it would provide more control.

> Also, I don't think it is sufficient for the type to just implement display.

Agreed.

**Comment by vitiral** [comment]
I can think of cases that you would want to have access to the full `Fmt` object, the main one comming to mind is if you wanted to format a container (i.e. a Vec) in a specal way.

You **could** use the `precision` to do something like this:

```
let args: HashMap = {"v": [1,2,3,4,5]}
let f = // closure which does the right thing
println!("{}", "vec: {v:.3?}".format_map(f))
```

This would output (for your library):
```
"[1, 2, 3, ...]"
```
In other words, you would use the precision to limit the number of **items** displayed instead of the number of characters.

This by itself is pretty compelling to me. Honestly, this could be used in some cases instead of the `println!` macro as it gives you a lot of power and control over how formatting happens.

**Comment by vitiral** [comment]
It looks like rust already exposes a lot of functionality in it's `Formatter` type. I think I should be using that:

https://doc.rust-lang.org/std/fmt/struct.Formatter.html

**Comment by vitiral** [comment]
I've looked into it more, going to take some notes here:


https://github.com/rust-lang/rust/blob/master/src/libfmt_macros/lib.rs
```
pub struct Argument<'a> {
    /// Where to find this argument
    pub position: Position<'a>,
    /// How to format the argument
    pub format: FormatSpec<'a>,
}
pub struct FormatSpec<'a>
    fill, align, etc
```
core/up/src/libcore/fmt/mod.rs
```
pub struct Formatter<'a>
```

I'm going to keep looking into this, but I think it is doable. The hardest thing will be packing the Formatter flags correctly.

**Comment by vitiral** [comment]
I've looked into it a bit and it looks like I **won't** be able to use function's implementation of `fmt` in order to format them dynamically (which makes sense... otherwise this library would probably be part of std already)

**Comment by vitiral** [comment]
Everything happens in 
https://doc.rust-lang.org/src/core/up/src/libcore/fmt/mod.rs.html
```
pub fn write(output: &mut Write, args: Arguments) -> Result 
```
So I would need access to write. Man, they've really tied this all super deep into the macro implementation. I wonder if that was really necessary.

I think the "magic" is happening with the `ArgumentV1`'s `value: Void` attribute:
```
pub struct ArgumentV1<'a> {
    value: &'a Void,
    formatter: fn(&Void, &mut Formatter) -> Result,
}
```
where `Void` is just defined as `enum Void {}`

I don't understand how they are managing to use void in this context to hold "dynamic values" -- what is even going on? What does an empty enum do?

Anyway, this is looking like a pretty rough route to implementing this library.

**Comment by vitiral** [comment]
The latest push to master has these changes, please take a look. I want some feedback before I publish to Cargo.

**Comment by theMonttu** [comment]
Looks good, I don't think I have anything to say really.

Are you are planning to implement more methods for `Formatter` for other types than `&str` later?

Using `Void` like that seems really weird, since as far as I know empty enums are impossible to create. That's why it is used to inform the compiler that something will never happen. https://github.com/reem/rust-void

**Comment by vitiral** [comment]
cool. I'm going to add a few more tests related to the fact that it can now handle integer syntax, but it should raise errors for strings, and then I'll push it up.

Yes, `Formatter` is now made to easily be able to add methods that can support non-str inputs. I will be writting documentation on the README calling for help on this (and how it can be easily implemented) as I don't have the time to do it in a quality manner ATM. Anyone who needs that functionality could easily add it though, now that the formatter reads the full format string :)

**Comment by vitiral** [comment]
The documentation still needs to be updated, but everything is in `strfmt v0.1.4` on Cargo. Thanks for the help!
