### ISSUE TITLE
Support JSON string as input text

### ISSUE THREAD

**Issue by aJesus37** [vitiral/strfmt#22]
I have a context where I need to apply the `.format(&values)` to a stringfied JSON, but I always end up with an error `Invalid("extra { found")`. 

If I understood correctly, characters `{` and `}` must have no other occurrences in the string to be able to use the format, is that correct? If so, is there a way to "escape" the other brackets? Or maybe use double brackets for the templating, similar to jinja on python.

Input I'm using:

```yaml
payload: >
    {"field":"IP Being blocked", "value":"{IP}"}
```

**Comment by vitiral** [comment]
You should be able to use `{{"my": "json"}}`
