### ISSUE TITLE
Behaviour of f64 formatting differs from std::fmt

### ISSUE THREAD

**Issue by Hero9909** [vitiral/strfmt#23]
via `std::fmt` a number like `42f64` formatted via `hello {:.3}` would look like `hello 42.000`,
but formated via strfmt it results in `hello 42`

is this behaviour intended or described anywhere?

**Comment by vitiral** [comment]
Not intended, probably just a bug. I'm not personally maintaining this library anymore but I will accept pull requests with tests that prove functionality.
