### ISSUE TITLE
Trailing comma in strfmt arg list will produce hard to track compiler error

### ISSUE THREAD

**Issue by KnorrFG** [vitiral/strfmt#28]
Hey, 
first, let me say: thanks for this library, it is really handy for code generation :)

I found a problem that might be considered a bug. A trailing comma in the argument list of strfmt will produce a compiler error. Normal rust functions allow a trailing comma, so it might be a good idea to allow this here too. But if you don't want to allow it, it would be nice if the error would show up where the trailing comma is missing, instead of in macros.rs

Example:
```rust
use strfmt::strfmt;
fn main() {
    let working = strfmt!("This {verb}", verb => "works").unwrap();
    let not_working = strfmt!("This {verb}", verb => "produces a compiler error",).unwrap();
}
```
compiling this will produce the following error:

```
felix@TP-Felix:/tmp/strfmt_err_demo$ cargo run
   Compiling strfmt_err_demo v0.1.0 (/tmp/strfmt_err_demo)
error: unexpected end of macro invocation
  --> /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/strfmt-0.2.2/src/macros.rs:48:31
   |
48 |         strfmt_builder!($vars,$($values)*)
   |                               ^ missing tokens in macro arguments

error: could not compile `strfmt_err_demo` due to previous error
```

**Comment by vitiral** [comment]
Hey, thanks!

I'm not actively maintaining this (or writing rust code) but I would accept a pull request with tests

It looks like this should be fairly simple: https://stackoverflow.com/questions/43143327/how-to-allow-optional-trailing-commas-in-macros

**Comment by KnorrFG** [comment]
Alright, I'll try my hands on it.
