### ISSUE TITLE
strfmt_map takes Fn, instead of FnMut, which is limiting

### ISSUE THREAD

**Issue by luketpeterson** [vitiral/strfmt#31]
I need to get additional information about the format string, such as a list of the keys embedded.  For example:

```rust
        let mut keys = HashSet::new();
        let formatter = |fmt: Formatter| {
            match fmt.key.parse::<String>() {
                Ok(key) => {
                    keys.insert(key);
                },
                Err(_) => {
                    return Err(FmtError::KeyError(format!("Invalid key: {}", fmt.key)));
                }
            };
            fmt.skip()
        };
        let _ = strfmt_map(text, &formatter)?;
```

Unfortunately, `strfmt_map` takes an `Fn` closure.  There is good precedent for other `map` methods to take an `FnMut` closure.  For example, `Iterator::map` https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.map

I opened a PR for this change.

Thank you.

**Comment by vitiral** [comment]
published in v0.2.4
