### ISSUE TITLE
&dyn DisplayStr doesn't implement DisplayStr, forcing user to box heterogeneous inputs

### ISSUE THREAD

**Issue by luketpeterson** [vitiral/strfmt#32]
The following code would work if &dyn DisplayStr implemented DisplayStr

```rust
    let template = "{body} = {some_number:2.4}";

    let mut data: HashMap<String, &dyn DisplayStr> = HashMap::new();
    data.insert("body".to_string(), &"This is a string");
    data.insert("some_number".to_string(), &5.0);

    let output = strfmt(template, &data)?;
```

A HashMap of &dyn DisplayStr is more efficient than the current best solution for heterogeneous input types, which is Box<dyn DisplayStr>, because each box requires a separate allocation.

I will submit a PR.

Thank you.

**Comment by vitiral** [comment]
published in v0.2.4
